mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from posting.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),
    path('posting/', include('posting.urls')),
    path('account/', include('account.urls')),
    path('user_profile/', include('user_profile.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posting/urls.py
from django.urls import path, re_path
from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'posting'

urlpatterns = [

    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('category/<int:category_id>/', base_views.catlistbyid, name='category'),


    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_view.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),


    # comment_view.py
    # comment_view.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_view.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

user_profile/urls.py
from django.urls import path, re_path
from .views import ShowProfilePageView, CreateProfilePageView, \
                    EditProfilePageView

app_name = 'user_profile'

urlpatterns = [
    re_path(r'^(?P<pk>\d+)/profile/$', ShowProfilePageView.as_view(), name='show_profile'),
    path('create_profile/', CreateProfilePageView.as_view(), name='create_profile'),
    re_path(r'^(?P<pk>\d+)/edit_profile/$', EditProfilePageView.as_view(), name='edit_profile'),

]

posting/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return '%s' % self.name

class Ip(models.Model):
    # 다음에는 models.GenericIPAddressField를 이용한다.
    ip = models.CharField(max_length=50)

    def __str__(self):
        return self.ip


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True, related_name='category_question')
    # 특정사용자가 추천한 질문을 얻기 위한 코드: some_user.voter_question.all()
    views = models.ManyToManyField(Ip, related_name='ip_question', blank=True, default=0)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

posting/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

from ..models import Question, Answer
from ..forms import AnswerForm


@login_required(login_url='account:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # return redirect('posting:detail', question_id=question_id)
            return redirect('{}#answer_{}'.format(
                 resolve_url('posting:detail', question_id=question_id), answer.id))


@login_required(login_url='account:login')
def answer_modify(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '답글을 수정 할 권한이 없습니다')
        return redirect('posting:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('posting:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'posting/answer_form.html', context)


@login_required(login_url='account:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '답글을 삭제 할 권한이 없습니다')
    else:
        answer.delete()
    return redirect('posting:detail', question_id=answer.question.id)

posting/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count, F

from ..models import Question, Answer, Category, Ip
from user_profile.models import Profile


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):

    # 입력인자
    page = request.GET.get('page', '1')
    keyword = request.GET.get('keyword', '')
    sort_type = request.GET.get('sort_type', 'recent')


    # 정렬 (추천순 // 답글 갯수순 // 작성순서순
    if sort_type == 'recommend':
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif sort_type == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')


    # 조회
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword) |
            Q(content__icontains=keyword) |
            Q(author__username__icontains=keyword) |
            Q(answer__author__username__icontains=keyword)
        ).distinct()

    #페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'keyword': keyword, 'sort_type': sort_type}
    return render(request, 'posting/question_list.html', context)



def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    # 답글 페이징 처리
    page = request.GET.get('page', 1)
    paginator = Paginator(question.answer_set.all(), 5)
    page_obj = paginator.get_page(page)

    # ip 가져오기
    ip = get_client_ip(request)

    # 페이징 뷰(조회수)를 위한 IP 검사 시작
    if Ip.objects.filter(ip=ip).exists():

        q1 = Question.objects.get(pk=question_id)
        q1.views.add(Ip.objects.get(ip=ip))

    else:
        Ip.objects.create(ip=ip)
        q1 = Question.objects.get(pk=question_id)
        q1.views.add(Ip.objects.get(ip=ip))


    context = {'question': question, 'answer_list': page_obj, 'page': page}


    # answer 정렬 -> 미구현

    # 작성자 가져오기
    print("1.Question-User:" )


    return render(request, 'posting/question_detail.html', context)


# 좀 더 적절한 구현이 필요. 코드가 반복되고 있다.
def catlistbyid(request, category_id):

    # 입력인자
    page = request.GET.get('page', '1')
    keyword = request.GET.get('keyword', '')
    sort_type = request.GET.get('sort_type', 'recent')

    # 정렬
    if sort_type == 'recommend':
        question_list = Question.objects.filter(category__id=category_id).annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif sort_type == 'popular':
        question_list = Question.objects.filter(category__id=category_id).annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.filter(category__id=category_id).order_by('-create_date')

    # 조회
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword) |
            Q(content__icontains=keyword) |
            Q(author__username__icontains=keyword) |
            Q(answer__author__username__icontains=keyword)
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    question_list = Question.objects.filter(category__id=category_id)
    context = {'category_id':category_id, 'question_list': page_obj, 'page': page, 'keyword': keyword, 'sort_type':sort_type}
    return render(request, 'posting/category.html', context)

posting/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

from ..models import Question, Answer, Comment
from ..forms import CommentForm



@login_required(login_url='account:login')
def comment_create_question(request, question_id):
    """
    질문 댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            #return redirect('posting:detail', question_id=question.id)
            return redirect('{}#comment_{}'.format(resolve_url('posting:detail',
                                                               question_id=comment.question.id), comment.id))

    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'posting/comment_form.html', context)


@login_required(login_url='account:login')
def comment_modify_question(request, comment_id):
    """
    질문 댓글 변경
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '답글을 수정 할 권한이 없습니다')
        return redirect('posting:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            #return redirect('posting:detail', question_id=comment.question.id)
            return redirect('{}#comment_{}'.format(resolve_url('posting:detail',
                                                               question_id=comment.question.id), comment.id))

    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'posting/comment_form.html', context)


@login_required(login_url='account:login')
def comment_delete_question(request, comment_id):
    """
    댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글을 삭제 할 권한이 없습니다')
        return redirect('posting:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('posting:detail', question_id=comment.question.id)


@login_required(login_url='account:login')
def comment_create_answer(request, answer_id):
    """
    답변 댓글 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('posting:detail',
                                                               question_id=comment.answer.question.id), comment.id))

    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'posting/comment_form.html', context)


@login_required(login_url='account:login')
def comment_modify_answer(request, comment_id):
    """
    질문 댓글 변경
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '답글을 수정 할 권한이 없습니다')
        return redirect('posting:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('posting:detail',
                                                               question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'posting/comment_form.html', context)


@login_required(login_url='account:login')
def comment_delete_answer(request, comment_id):
    """
    댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글을 삭제 할 권한이 없습니다')
        return redirect('posting:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('posting:detail', question_id=comment.answer.question.id)

posting/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer

@login_required(login_url='account:login')
def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')

    else:
        question.voter.add(request.user)

    return redirect('posting:detail', question_id=question_id)



@login_required(login_url='account:login')
def vote_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')

    else:
        answer.voter.add(request.user)

    return redirect('posting:detail', question_id = answer.question.id)

templates/posting/answer_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/posting/comment_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/posting/question_detail.html
{% extends 'base.html' %}
{% load posting_filter %}
{% block content %}


<div class="container my-3">

    <!-- 사용자 오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>

    <div class="row my-3">
        <div class="col-1">
            <a href="{% url 'posting:vote_question' question.id %}"  class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ question.voter.count }}</div>
        </div>

    <div class="col-11">
        <div class="card">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ question.content|mark }}</div>
                <div class="d-flex justify-content-end">
                      <div class="badge badge-light p-2 text-left">
                          <div class="mb-2">작성일: {{ question.create_date }}</div>
                          <div class="mb-2">
                              {% if question.author.profile.profile_pic %}
                                <img src="{{ question.author.profile.profile_pic.url }}" width=50 height=50 class="rounded">
                              {% else %}
                                No image
                              {% endif %}
                              <a href="{% url 'user_profile:show_profile' question.author.profile.user.id %}" >{{ question.author.username }}</a></div>
                          </div>
                    {% if question.modify_date %}
                          <div class="mb-2">수정일: {{ question.modify_date }}</div>
                    {% endif %}

                      </div>
                </div>
                {% if request.user == question.author %}
                <div class="my-3">
                    <a href="{% url 'posting:question_modify' question.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'posting:question_delete' question.id %}">삭제</a>
                </div>
                {% endif %}


                <!-- 질문댓글보이기 시작 -->
                {% if question.comment_set.count > 0 %}
                <div class="mt-3">
                    {% for comment in question.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.comment_content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정: {{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'posting:comment_modify_question' comment.id %}" class="small">수정</a>,
                            <a href="#" class="small delete" data-uri="{% url 'posting:comment_delete_question' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
            <!-- 질문 댓글 작성 -->
                {% if user.is_authenticated %}
                <div class="child-comment">
                        <form action="{% url 'posting:comment_create_question' question.id %}" method="post" class="post-form my-3">
                            {% csrf_token %}
                            {% include "form_errors.html" %}
                            <div class="form-group">
                                <label for="comment_content"></label>
                                <textarea class="form-control" name="comment_content" id="comment_content" rows="3">{{ form.comment_content.value|default_if_none:'' }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">댓글저장</button>
                        </form>
                </div>
                {% endif %}

            </div>




        <!-- 질문댓글 끝 -->
         </div>
        </div>




    <h5 class="border-bottom my-3 py-2">
        댓글 | 총 {{ question.answer_set.count }} 개
    </h5>


    <!-- 답글 시작 -->
    {% for answer in answer_list %}
    <!-- 질문상세 화면에 앵커 엘리먼트 추가하기 -->
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <a href="#" data-uri="{% url 'posting:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>

        </div>

        <!-- 답변영역 -->
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">{{ answer.modify_date }}에 수정됨</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">


                            <div class="mb-2">작성일: {{ answer.create_date }}</div>
                            <div class="mb-2">
                              {% if answer.author.profile.profile_pic %}
                                <img src="{{ answer.author.profile.profile_pic.url }}" width=50 height=50 class="rounded">
                              {% else %}
                                No image
                              {% endif %}
                                <a href="{% url 'user_profile:show_profile' answer.author.profile.user.id %}" >{{ answer.author.username }}</a></div>
                              </div>

                        </div>
                    </div>


                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'posting:answer_modify' answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                           data-uri="{% url 'posting:answer_delete' answer.id  %}">삭제</a>
                    </div>
                    {% endif %}
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'posting:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'posting:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'posting:comment_create_answer' answer.id  %}"
                           class="small"><small> 댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


    <form action="{% url 'posting:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>

        <div class="d-flex justify-content-between">
        <input type="submit" value="답변등록" class="btn btn-primary">
        <a href="{% url 'posting:index' %}" class="btn btn-secondary"> 글목록 </a>
        </div>
    </form>


    <!-- 답글 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if answer_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">처음</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.previous_page_number }}"><<</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>

        {% endif %}

        <!-- 페이지 리스트 -->
        {% for page_number in answer_list.paginator.page_range %}
            {% if page_number >= answer_list.number|add:-5 and page_number <= answer_list.number|add:5 %}
                {% if page_number == answer_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>

                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if answer_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.next_page_number }}">>></a>
        </li>

        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.paginator.num_pages }}">끝</a>
        </li>

        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">>></a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">끝</a>
        </li>
        {% endif %}
        <!-- 맨마지막 -->
    </ul>

    <!-- 페이징 처리 끝 -->
</div>


{% endblock %}
{% block script %}

<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/posting/question_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors  %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            <label for="category">분류</label>
            {{ form.category }}
        </div>


        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>

        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="5">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>

{% endblock %}