mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from posting.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),
    path('posting/', include('posting.urls')),
    path('account/', include('account.urls')),
    path('user_profile/', include('user_profile.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path, re_path
from .views import ShowProfilePageView, CreateProfilePageView, \
                    EditProfilePageView

app_name = 'user_profile'

urlpatterns = [
    re_path(r'^(?P<pk>\d+)/profile/$', ShowProfilePageView.as_view(), name='show_profile'),
    path('create_profile/', CreateProfilePageView.as_view(), name='create_profile'),
    re_path(r'^(?P<pk>\d+)/edit_profile/$', EditProfilePageView.as_view(), name='edit_profile'),

]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    bio = models.TextField(blank=True)
    profile_pic = models.ImageField(blank=True, default="images/profile/default_profile_pic.jpg",
                                    upload_to="images/profile/")
    website_url = models.CharField(max_length=200, blank=True, default='')
    facebook_url = models.CharField(max_length=200, blank=True, default='')
    twitter_url = models.CharField(max_length=200, blank=True, default='')

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('index')

user_profile/forms.py
from django import forms
from .models import Profile


class CreateUserProfileForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False, error_messages={'invalid': ("Image files only")},
                                   widget=forms.FileInput)
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'website_url', 'facebook_url', 'twitter_url']
        labels = {
            'bio': '소개',
            'profile_pic': '프로필사진',
            'website_url': '개인웹사이트',
            'facebook_url': '페이스북',
            'twitter_url' : '트위터',
        }
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 5, 'cols': 50}),
            'website_url': forms.Textarea(attrs={'class': 'form-control', 'rows': 1, 'cols': 10}),
            'facebook_url': forms.Textarea(attrs={'class': 'form-control'}),
            'twitter_url': forms.Textarea(attrs={'class': 'form-control'}),
        }


# 에디트 폼 클래스 구현
class EditUserProfileForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False, error_messages= {'invalid': ("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'website_url', 'facebook_url', 'twitter_url']
        labels = {
            'bio': '소개',
            'profile_pic': '프로필사진',
            'website_url': '개인웹사이트',
            'facebook_url': '페이스북',
            'twitter_url' : '트위터',
        }
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 5, 'cols': 50}),
            'website_url': forms.Textarea(attrs={'class': 'form-control', 'rows': 1, 'cols': 10}),
            'facebook_url': forms.Textarea(attrs={'class': 'form-control', 'rows': 1, 'cols': 10}),
            'twitter_url': forms.Textarea(attrs={'class': 'form-control', 'rows': 1, 'cols': 10}),
        }

user_profile/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import AccessMixin
from django.views import generic
from django.urls import reverse_lazy
from .forms import CreateUserProfileForm, EditUserProfileForm

from .models import Profile
from posting.models import Question, Answer, Comment

# 프로필 보이기(클래스 베이스)

class OwnerOnlyMixin(AccessMixin):
    raise_exception = True
    permission_denied_message = "사용 권한이 없습니다"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if request.user != obj.user:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class ShowProfilePageView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'user_profile/show_profile.html'

    def get_context_data(self, *args, **kwargs):
        # users = Profile.objects.all()
        context = super(ShowProfilePageView, self).get_context_data(*args, **kwargs)
        page_user = get_object_or_404(Profile, id=self.kwargs['pk'])
        context["page_user"] = page_user

        # 특정유저의 질문 갯수 저장
        context["num_questions"] = Question.objects.filter(author__id = page_user.id).count()
        # 특정유저의 답글 갯수 저장
        context["num_answers"] = Answer.objects.filter(author__id=page_user.id).count()
        # 특정유저의 댓글 갯수 저장
        context["num_comments"] = Comment.objects.filter(author__id=page_user.id).count()

        return context

# 프로필 생성
class CreateProfilePageView(OwnerOnlyMixin, generic.CreateView):
    model = Profile
    form_class = CreateUserProfileForm
    template_name = 'user_profile/create_profile.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

# 프로필 업데이트
class EditProfilePageView(OwnerOnlyMixin, generic.UpdateView):
    model = Profile
    form_class = EditUserProfileForm
    template_name = 'user_profile/edit_profile.html'
    # fields = ['bio', 'profile_pic', 'website_url', 'facebook_url', 'twitter_url']
    success_url = reverse_lazy('index')

templates/user_profile/create_profile.html
{% extends "base.html" %}
{% block content %}

        <div class="container my-3">
            <div class="row my-3">
                <div class="col-4">
                    <h4>프로필 생성</h4>
                </div>
            </div>

            <div>

            </div>

            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "form_errors.html" %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">확인</button>
            </form>
        </div>

{% endblock %}

templates/user_profile/edit_profile.html
{% extends "base.html" %}
{% block content %}

{% if user.is_authenticated %}
    {% if user.id == profile.user.id %}
        <div class="container my-3">
            <div class="row my-3">
                <div class="col-4">
                    <h4>프로필 변경</h4>
                </div>
            </div>

            <div>

            </div>

            <form enctype="multipart/form-data" method="post" class="post-form" >
                {% csrf_token %}
                {% include "form_errors.html" %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">확인</button>
            </form>
        </div>

    {% else %}
    <h1> 프로필을 수정할 권한이 없습니다. </h1>
    {% endif %}

{% else %}
<h1> 잘못된 페이지 접근입니다.</h1>
{% endif %}
{% endblock %}

templates/user_profile/show_profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<br><br>

<br><br>
<div class="container my-3">
    <h5> 사용자 프로필 </h5>
<div class="card mb-3">
    <div class="row no-gutters">
        <div class="col-md-2">
            {% if page_user.profile_pic %}
            <img src="{{ profile.profile_pic.url }}" class="card-img-top">
            {% else %}
            <div>No_image</div>
            {% endif %}
        </div>

        <div class="col-md-10">
            <div class="card-body">
                <h5 class="card-title">
                    {{ page_user }}
                </h5>
        <p class="card-text">
            {{ page_user.bio }}
        </p>

         <p class="card-text">
             질문 횟수: {{ num_questions }}
        </p>

         <p class="card-text">
            답변 횟수: {{ num_answers }}
        </p>

        <p class="card-text">
            댓글 횟수: {{ num_comments }}
        </p>

            </div>
        </div>
    </div>
</div>

    <a class="btn btn-primary" href="{% url 'user_profile:edit_profile' user.profile.id %}">내프로필변경</a>

</div>



{% endblock %}