account/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import login_view, signup, find_email, \
                    result, change_password, \
                    password_change_done
from .kakao_login_view import kakao_logout, kakao_code_req, \
                            kakao_token_req


app_name = 'account'

urlpatterns = [
    path('login/', login_view.as_view(), name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('find_email/', find_email, name='find_email'),
    path('result/', result, name='result'),
    path('change_password/', change_password, name='change_password'),
    path('password_change_done/', password_change_done, name='password_change_done'),

    # 비밀번호 찾기 (수정 필요)
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="account/reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="account/reset_password_sent.html"),
         name="reset_password_sent"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/reset_password_form.html"),
         name="reset_password_form"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="account/reset_password_complete.html"),
         name="reset_password_complete"),

    # 카카오로그인
    path('kakao_code_req/', kakao_code_req, name='kakao_code_req'),
    path('kakao_token_req/', kakao_token_req, name='kakao_token_req'),
    path('kakao_logout/', kakao_logout, name='kakao_logout'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from posting.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),
    path('posting/', include('posting.urls')),
    path('account/', include('account.urls')),
    path('user_profile/', include('user_profile.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posting/urls.py
from django.urls import path, re_path
from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'posting'

urlpatterns = [

    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('category/<int:category_id>/', base_views.catlistbyid, name='category'),


    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_view.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),


    # comment_view.py
    # comment_view.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_view.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

user_profile/urls.py
from django.urls import path, re_path
from .views import ShowProfilePageView, CreateProfilePageView, \
                    EditProfilePageView

app_name = 'user_profile'

urlpatterns = [
    re_path(r'^(?P<pk>\d+)/profile/$', ShowProfilePageView.as_view(), name='show_profile'),
    path('create_profile/', CreateProfilePageView.as_view(), name='create_profile'),
    re_path(r'^(?P<pk>\d+)/edit_profile/$', EditProfilePageView.as_view(), name='edit_profile'),

]

posting/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count, F

from ..models import Question, Answer, Category, Ip
from user_profile.models import Profile


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):

    # 입력인자
    page = request.GET.get('page', '1')
    keyword = request.GET.get('keyword', '')
    sort_type = request.GET.get('sort_type', 'recent')


    # 정렬 (추천순 // 답글 갯수순 // 작성순서순
    if sort_type == 'recommend':
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif sort_type == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')


    # 조회
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword) |
            Q(content__icontains=keyword) |
            Q(author__username__icontains=keyword) |
            Q(answer__author__username__icontains=keyword)
        ).distinct()

    #페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'keyword': keyword, 'sort_type': sort_type}
    return render(request, 'posting/question_list.html', context)



def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    # 답글 페이징 처리
    page = request.GET.get('page', 1)
    paginator = Paginator(question.answer_set.all(), 5)
    page_obj = paginator.get_page(page)

    # ip 가져오기
    ip = get_client_ip(request)

    # 페이징 뷰(조회수)를 위한 IP 검사 시작
    if Ip.objects.filter(ip=ip).exists():

        q1 = Question.objects.get(pk=question_id)
        q1.views.add(Ip.objects.get(ip=ip))

    else:
        Ip.objects.create(ip=ip)
        q1 = Question.objects.get(pk=question_id)
        q1.views.add(Ip.objects.get(ip=ip))


    context = {'question': question, 'answer_list': page_obj, 'page': page}


    # answer 정렬 -> 미구현

    # 작성자 가져오기
    print("1.Question-User:" )


    return render(request, 'posting/question_detail.html', context)


# 좀 더 적절한 구현이 필요. 코드가 반복되고 있다.
def catlistbyid(request, category_id):

    # 입력인자
    page = request.GET.get('page', '1')
    keyword = request.GET.get('keyword', '')
    sort_type = request.GET.get('sort_type', 'recent')

    # 정렬
    if sort_type == 'recommend':
        question_list = Question.objects.filter(category__id=category_id).annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif sort_type == 'popular':
        question_list = Question.objects.filter(category__id=category_id).annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.filter(category__id=category_id).order_by('-create_date')

    # 조회
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword) |
            Q(content__icontains=keyword) |
            Q(author__username__icontains=keyword) |
            Q(answer__author__username__icontains=keyword)
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    question_list = Question.objects.filter(category__id=category_id)
    context = {'category_id':category_id, 'question_list': page_obj, 'page': page, 'keyword': keyword, 'sort_type':sort_type}
    return render(request, 'posting/category.html', context)

templates/base.html
{% load static %}

<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>My_Homepage</title>
</head>
<body>
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous">
</script>

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- Javascript Start -->
{% block script %}
{% endblock %}

</body>
</html>

templates/form_errors.html
<!-- 로그인 실패시 그 원인을 알려주는 html -->

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 내비게이션 바 -->

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'posting:index' %}">Home</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posting:category' '1' %}">Django</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posting:category' '2' %}">알고리즘</a>
            </li>
        </ul>
    </div>


    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    {% if user.profile %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user_profile:show_profile' user.profile.id %}">내프로필</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user_profile:create_profile' %}">프로필만들기</a>
                        </li>
                    {% endif %}
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'account:logout' %}"> 로그아웃 </a>
                <a class="dropdown-item" href="{% url 'account:change_password' %}"> 비밀번호변경 </a>
                </div>
                {% else %}
                    <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>